Creation de la base de donnée we_share et ajout de données de test
WildCodeSchool/tours-php-2009-project2-weshare pull request #1
Opened 2020-10-27 15:44 UTC by CeliaBoiss

2020-10-27 17:12 UTC, KevinRoig commented on db_weshare.sql
> +UNLOCK TABLES;
Est-ce que ça ne devrait pas être enlevé?

2020-10-27 17:15 UTC, KevinRoig requested changes
J'ai mis une annotation sur des lignes qui ne me paraissent pas à leur place, qu'en penses-tu?

2020-10-28 08:47 UTC, CeliaBoiss commented on db_weshare.sql
> +UNLOCK TABLES;
On a finalement dit qu'on gardait la table pour servir d'exemple. On l'effacera plus tard quand on aura avancé, ok ?

2020-10-28 08:59 UTC, KevinRoig commented
Review ok, changes are validated with Celia.

2020-10-28 09:01 UTC, KevinRoig submitted a review, later dismissed
Ok, checked with Celia.

2020-10-28 14:18 UTC, RomainClair requested changes
You probably should use english names for tables, fields, variable names, comment etc...

2020-10-28 14:18 UTC, RomainClair commented on db_weshare.sql
> +DROP TABLE IF EXISTS `adresse`;
shouldn't table names be in english ?

2020-10-28 14:18 UTC, RomainClair commented on db_weshare.sql
> +  `fk_ville_id` int DEFAULT NULL,
And table fields ?

2020-10-28 15:28 UTC, RomainClair requested changes
Some names could be rephrased

2020-10-28 15:28 UTC, RomainClair commented on db_weshare.sql
> +  `request_date_end` date DEFAULT NULL,
Seems strange to use the table name as a prefix for all the table fields...

2020-10-28 15:28 UTC, RomainClair commented on db_weshare.sql
> +DROP TABLE IF EXISTS `adress`;
Isn't it "address" in english ? =)

2020-10-28 15:28 UTC, RomainClair commented on db_weshare.sql
> +  `user_email` varchar(50) NOT NULL,
It's the same. It's unnecessary to prefix fields by the table name. They already are in the table.

2020-10-29 08:52 UTC, RomainClair approved these changes
You probably should explain users and/or developpers what they are supposed to do with this sql file. May be update README.md ?

2020-10-29 09:18 UTC, KevinRoig approved these changes
It's ok for me.

2020-10-29 09:18 UTC, merged