Pr master
WildCodeSchool/tours-php-2009-project2-weshare pull request #10
Opened 2020-11-10 10:40 UTC by CeliaBoiss

2020-11-10 12:05 UTC, Quentin-BLANC requested changes
I leave a comment public/assets/css/seeRequestStyleSheet.css line 185.

2020-11-10 12:05 UTC, Quentin-BLANC commented on public/assets/css/seeRequestStyleSheet.css
> +    overflow: visble;
visible

2020-11-10 13:56 UTC, Quentin-BLANC submitted a review, later dismissed

2020-11-12 12:42 UTC, RomainClair requested changes
There's no installation manual for the project.
It could be an update of README.md or something equivalent (INSTALL.md etc...)
If someone follow the readme.md instructions, the project won't work because of the database schema.

2020-11-12 13:32 UTC, Quentin-BLANC approved these changes

2020-11-13 07:34 UTC, RomainClair approved these changes

2020-11-13 07:34 UTC, merged