Registration form
WildCodeSchool/tours-php-2009-project2-weshare pull request #5
Opened 2020-10-30 14:12 UTC by CeliaBoiss

The security verifications are not done but will be in a future PR

2020-10-30 14:37 UTC, leobro7 approved these changes, later dismissed
it's ok!

2020-11-04 11:08 UTC, leobro7 submitted a review, later dismissed
ok

2020-11-04 14:37 UTC, RomainClair requested changes
The .DS_Store directory is a mac os configuration directory.
It must not be commited in the git repository.

You probably should specify the type your parameters & functions

You could replace magic numbers with constants.

2020-11-04 14:37 UTC, RomainClair commented on src/Controller/UserController.php
> +            && isset($_POST['street']) && isset($_POST['townId']) && isset($_POST['email'])) {
You could have only one if

2020-11-04 14:37 UTC, RomainClair commented on src/Model/User.php
> +        return $this->errors;
isOk returns the errors array ? the name could be more accurate. getErrors for example

2020-11-04 14:37 UTC, RomainClair commented on src/Model/User.php
> +        if (!preg_match("#^[a-z0-9._-]+@[a-z0-9._-]{2,}\.[a-z]{2,4}$#i", $email)) {
Validating email is hard.
You probably should use a specialized tool. PHP has one with the FILTER_VALIDATE_EMAIL

2020-11-04 14:37 UTC, RomainClair commented on src/Model/User.php
> +        if (strlen($phone) != 10) {
No dotted phone number ?

2020-11-04 14:37 UTC, RomainClair commented on src/Model/User.php
> +        $this->setEmail(trim($email));
It could be better to trim directly in the setters than in the construct only

2020-11-04 14:37 UTC, RomainClair commented on src/Model/TownManager.php
> + */
It's probably wrong.

2020-11-04 14:37 UTC, RomainClair commented on src/Model/TownManager.php
> + */
Empty comments should be removed, or better, completed

2020-11-04 14:37 UTC, RomainClair commented on src/Controller/UserController.php
> +                if (empty($errors)) {
You should probably have a isValid() and a getErrors() method in the User class

2020-11-04 14:37 UTC, RomainClair commented on src/Controller/UserController.php
> +                    $userManager->insert($user);
At this point, maybe you should have an UserManager::insert method taking a User parameter instead of an array

2020-11-04 14:37 UTC, RomainClair commented on src/Controller/UserController.php
> +                $errors['notFull'] = 'Veuillez remplir tous les champs du formulaire.';
You probably should have a User::isIncomplete() method to check that

2020-11-04 14:37 UTC, RomainClair commented on src/Controller/UserController.php
> +            ['tables' => [['towns' => $towns],['errors' => $errors]]]
You should have only one array with multiple twig variables

2020-11-05 08:34 UTC, leobro7 approved these changes

2020-11-05 13:40 UTC, RomainClair approved these changes
You shouldn't echo in you controller but return a view instead.
You should stop a controller after a redirect header and not render an entire view.

2020-11-05 13:41 UTC, merged